# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ots
    main: .
    binary: ots
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'github.com/skymeyer/onetime-secret/cmd.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  split: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    ## Container image

    `gcr.io/skymeyer/onetime-secret:{{ .Version }}`
